<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	<Version>1.1.0.2</Version>
	<AssemblyVersion>1.1.0.2</AssemblyVersion>
	<FileVersion>1.1.0.2</FileVersion>
    <AssemblyName>Jellyfin.Plugin.Trombee</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.Trombee</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <CodeAnalysisRuleSet>../jellyfin.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.8" >
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="10.11.8">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.11" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SerilogAnalyzer" Version="0.15.0" PrivateAssets="All" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" PrivateAssets="All" />
    <PackageReference Include="SmartAnalyzers.MultithreadingAnalyzer" Version="1.1.31" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\Sql\**\*.sql" />
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <None Remove="Configuration\actorsBrowse.html" />
    <EmbeddedResource Include="Configuration\actorsBrowse.html" />
    <None Remove="Images\channel_icon.png" />
    <EmbeddedResource Include="Images\channel_icon.png" />
    <None Remove="Images\thumb.png" />
    <EmbeddedResource Include="Images\thumb.png">
      <LogicalName>Jellyfin.Plugin.Trombee.thumb.png</LogicalName>
    </EmbeddedResource>
    <Content Include="Images\thumb.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <TargetPath>thumb.png</TargetPath>
    </Content>
    <Content Include="meta.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
